name: Discover API with Javascript

on: [pull_request, workflow_dispatch, push]

jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruairi-hayes/apic-discovery-action@main
      id: discover-apis
      with:
        milliseconds: 5000
        api_host: d-h01.apiconnect.dev.automation.ibm.com
        provider_org: 'ruairi_h01_b'
        api_key: ${{ secrets.apicApikey }}
        api_file: gmail-api.json
    - name: Display the action-result
      run: |
        echo "Result of the action: ${{ steps.discover-apis.outputs.action-result }}"