name: Create draft API with Javascript

on: [pull_request, workflow_dispatch]

jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruairi-hayes/apic-discovery-action@main
      with:
        milliseconds: 5000